name: sitech_books
description: SiTech's task about a paginated list of books with offline cabablity.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  lottie: ^2.2.0
  once: ^1.5.0
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/